<Project>

  <PropertyGroup>
    <LangVersion>14</LangVersion>
    <Nullable>enable</Nullable>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.1.1" PrivateAssets="All" />
  </ItemGroup>

  <!-- Workaround for https://github.com/dotnet/sourcelink/issues/572 -->
  <ItemGroup>
    <SourceRoot Include="$(MSBuildThisFileDirectory)/" />
  </ItemGroup>

</Project>
