name: release
on:
  release:
    types: [published]

jobs:
 windows:
    runs-on: windows-latest
    if: "!github.event.release.prerelease"
    steps:
    - uses: actions/checkout@v3
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      shell: bash
    - run: echo ${{ steps.get_version.outputs.VERSION }}
    - run: dotnet pack src/NetMQ/NetMQ.csproj -o . -c Release /p:PackageVersion=${{ steps.get_version.outputs.VERSION }} /p:Version=${{ steps.get_version.outputs.VERSION }} /p:ContinuousIntegrationBuild=true
    - run: dotnet nuget push *.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
      env:
        NUGET_API_KEY: ${{ secrets.NuGetAPIKey }}
      shell: bash
          

